### ISSUE TITLE
hello krumo

### ISSUE THREAD

**Issue by zhengniuniu** [krumo/emodbSER#1]
hello krumo,
    I have reed your code about speech emotion recognition on EmoDB database,i have a question that how to get the database of emodb.pkl.

**Comment by krumo** [comment]
hi @zhengniuniu , I have uploaded a read_emodb.py file to the repository, which could read the original EmoDB into a .pkl file. Hope it can help you.

**Comment by zhengniuniu** [comment]
Thank you for sharing
