### ISSUE TITLE
新人提一个小问题

### ISSUE THREAD

**Issue by EdenTu** [krumo/emodbSER#3]
你好，
    最近刚开学才开始语音识别研究，请问下：
    1、cae.py里的line180和line181的两个文件：‘enterface.pkl’和'savee.pkl'文件是什么呢？代码里没有啊；
    2、跑cnn.py显示line105和line144报错：‘could not broadcast input array from shape (65536) into shape (39216)’，怎么解决呢？

    期待您的回复，谢谢！！

**Comment by krumo** [comment]
1. enterface.pkl和savee.pkl是另外两个语音数据集，因为emodb数据集的数据量不够大，之前我曾经尝试过使用其它语音数据集进行预训练，但是结果不够理想，所以没有出现在代码中。
2. 因为语音数据集文件太大了，并不适合上传到github上，所以在仓库中我只上传了我的代码，由于我并不清楚你是怎么提取emodb的数据特征的，因此我可能也没有办法准确地帮到你。针对你的问题，你可以尝试使用read_emodb.py读取emodb的特征，生成emodb.pkl文件，再运行cnn.py。

**Comment by EdenTu** [comment]
十分感谢解答！！
